# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Docker Image CI for GHCR

on:
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: build and push the image
        run: |
          docker login --username hrenovo --password ${{secrets.GITHUB_TOKEN}} ghcr.io
          docker build . --tag ghcr.io/hrenovo/coophive-module-cowsay:v3.0.3
          docker push ghcr.io/hrenovo/coophive-module-cowsay:v3.0.3
